---
dist: minimal
services: docker
env:
  global:
    - DOCKER_ORGANISATION: nuevolia    
    - DOCKER_REPOSITORY: java
  matrix:
    - DOCKER_BASE_IMAGE: centos7
    - DOCKER_BASE_IMAGE: centos6
    - DOCKER_BASE_IMAGE: ubuntu1804
    - DOCKER_BASE_IMAGE: ubuntu1604

before_install:
  # Upgrade Docker.
  - sudo apt-get -yqq update
  - sudo apt-get -yq -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t ${DOCKER_ORGANISATION}/${DOCKER_REPOSITORY}:${DOCKER_BASE_IMAGE} -f Dockerfile.${DOCKER_BASE_IMAGE} ${PWD}
  - docker run --name test-container --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${DOCKER_ORGANISATION}/${DOCKER_REPOSITORY}:${DOCKER_BASE_IMAGE}
